# Generated by Django 4.2.5 on 2023-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='style',
            field=models.ManyToManyField(related_name='style_articles', to='articles.style'),
        ),
    ]
