# Generated by Django 4.2.5 on 2023-10-08 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='style',
        ),
        migrations.AddField(
            model_name='article',
            name='styles',
            field=models.ManyToManyField(related_name='articles', to='articles.style'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
