# Generated by Django 4.2.5 on 2023-10-12 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_article_author_alter_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='article',
            name='styles',
        ),
        migrations.AddField(
            model_name='article',
            name='styles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_articles', to='articles.style'),
        ),
    ]
