# Generated by Django 4.2.5 on 2023-10-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author_remove_article_styles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='styles',
            new_name='style',
        ),
    ]
