# Generated by Django 4.2.5 on 2023-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_style_article_styles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.product'),
        ),
    ]
