# Generated by Django 4.2.5 on 2023-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0003_alter_user_email_alter_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, related_name='style_users', to='articles.style'),
        ),
    ]
