# Generated by Django 4.2.5 on 2023-10-06 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_style'),
        ('accounts', '0004_rename_profile_image_user_image_user_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='style',
            field=models.ManyToManyField(related_name='style_users', to='articles.style'),
        ),
    ]
